### ISSUE TITLE
给star了，提几点小建议

### ISSUE THREAD

**Issue by lithiumleeow** [xtliuke/auto_brightness#1]
1.桌面端程序可以隐藏到任务栏
2.添加开机自启
3.手机端APP可以添加桌面时钟功能，在检测环境光的时候又能当作桌面时钟展示
还有效的避免了杀后台

**Comment by xtliuke** [comment]
谢谢大佬帮忙测试
这几点的确是非常实用，第二版会加进来

**Comment by xtliuke** [comment]
已解决，请下载1.1版本，谢谢您的提议
