### ISSUE TITLE
几点小建议

### ISSUE THREAD

**Issue by 0000000O** [xtliuke/auto_brightness#2]
1，屏幕亮度加入区间值，很多显示器的90%-100%亮度是无效的，最高亮度就是90%。
2，亮度调整的渐变现在还是比较突兀，希望能更平滑一些。
3，环境光最大亮度为啥才给1000啊，我经常测到2000多到30000

很好的程序。谢谢开发

**Comment by xtliuke** [comment]
谢谢大佬帮忙测试
亮度区间值这个很多小伙伴们也都提到了，这个在第二版会加进来
亮度渐变这个预计也会给个渐变时间调节，那样可以根据喜好调节渐变所需时间
环境光线原本我以为室内普遍值在300左右，所以这个只给了1000，超过一千就直接最亮了，这个我会做一些调整

**Comment by xtliuke** [comment]
@0000000O 已解决，请下载1.1版本，谢谢您的提议
