### ISSUE TITLE
小建议，安卓端 和 PC端

### ISSUE THREAD

**Issue by mustssr** [xtliuke/auto_brightness#3]
- 我的显示器低于5%亮度会非常暗，100%会去到600nt亮瞎眼，环境光我那手机中午开窗能到5000+

- PC
亮度和环境光都可以自定义最大最小值就完美了

- 安卓
手机是OLED的可以的话可以加个全屏权限，然后加个左或右全黑界面

**Comment by xtliuke** [comment]
明白，谢谢大佬帮忙测试，第二版这些都会加进来

**Comment by xtliuke** [comment]
已解决，请下载1.1版本，谢谢您的提议

**Comment by xtliuke** [comment]
已解决，请下载1.1版本，谢谢您的提议
